# Generated by Django 4.2.2 on 2023-10-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("miksi_apideck", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="user",
        ),
        migrations.RemoveField(
            model_name="room",
            name="company",
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
