# Generated by Django 4.2.2 on 2023-07-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_usersignup_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='user_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
