# Generated by Django 4.2.3 on 2023-08-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_room_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
