# Generated by Django 4.2.2 on 2023-06-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
