# Generated by Django 4.2.2 on 2023-06-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_apikey_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='status',
            new_name='active',
        ),
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
