# Generated by Django 4.2.2 on 2023-07-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_usersignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='id',
        ),
        migrations.AddField(
            model_name='usersignup',
            name='user_id',
            field=models.CharField(default=123456, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
