# Generated by Django 4.2.2 on 2023-07-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_usersignup_id_usersignup_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSignup',
        ),
    ]
