# Generated by Django 4.2.2 on 2023-07-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_usersignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSignup',
        ),
    ]
