# Generated by Django 4.2.2 on 2023-07-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_usersignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='csvfile',
            old_name='metadata',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.CharField(default='DEFAULT', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, to='companies.usersignup'),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='company_id',
            field=models.CharField(default='DEFAULT', max_length=8),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='user_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
