# Generated by Django 4.2.2 on 2023-07-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_rename_company_company_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='company_id',
            field=models.CharField(db_column='company_id', default='DEFAULT', max_length=8),
        ),
        migrations.RenameField(
            model_name='csvfile',
            old_name='company_id',
            new_name='file_company_id',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='company',
            field=models.ForeignKey(db_column='file_company', default=1235, on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.usersignup'),
        ),
    ]
