# Generated by Django 4.2.2 on 2023-07-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_csvfile_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='file_company_id',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='company_id',
            field=models.CharField(default='DEFAULT', max_length=8),
        ),
    ]
