# Generated by Django 4.2.2 on 2023-07-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_remove_csvfile_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='company_id',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='company',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to='companies.company'),
        ),
    ]
